//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class auteur
    {
        public int codeauteur { get; set; }
        public Nullable<int> numeroaut { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string tel { get; set; }
        public string adr { get; set; }
        public string email { get; set; }
        public string institution { get; set; }
        public string specialite { get; set; }
        public string ville { get; set; }
        public string codepostal { get; set; }
        public string web { get; set; }
        public byte[] image { get; set; }
        public string cin { get; set; }
        public string fax { get; set; }
    }
}
