//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bon_commande
    {
        public int id { get; set; }
        public Nullable<int> numero_bc { get; set; }
        public Nullable<System.DateTime> date_ajout { get; set; }
        public string etat { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<double> remise { get; set; }
        public Nullable<double> prixremise { get; set; }
        public string id_clt { get; set; }
        public string client { get; set; }
        public Nullable<int> numerodevis { get; set; }
        public string comment { get; set; }
    }
}
