//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int codeclient { get; set; }
        public Nullable<int> numerocl { get; set; }
        public string raisonsoc { get; set; }
        public string resp { get; set; }
        public string qualite { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string adresse { get; set; }
        public Nullable<int> codepostal { get; set; }
        public string ville { get; set; }
        public string web { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
    }
}
