//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumulEnt
    {
        public int code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idfr { get; set; }
        public string nomfr { get; set; }
        public Nullable<int> numerocumul { get; set; }
        public string type { get; set; }
    }
}
