//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossierpublication
    {
        public int id { get; set; }
        public string ndossier { get; set; }
        public string titre { get; set; }
        public string discipline { get; set; }
        public Nullable<int> idauteur { get; set; }
        public string auteur { get; set; }
        public Nullable<System.DateTime> datedepo { get; set; }
        public string support { get; set; }
        public Nullable<int> nbpage { get; set; }
        public string format { get; set; }
        public string formatpapierinter { get; set; }
        public Nullable<int> nbpagenormal { get; set; }
        public Nullable<int> nbpagecolor { get; set; }
        public string couverture { get; set; }
        public string finition { get; set; }
        public Nullable<int> nboncommande { get; set; }
        public Nullable<System.DateTime> datecommande { get; set; }
        public Nullable<int> idimp { get; set; }
        public string imp { get; set; }
        public string tirage { get; set; }
        public Nullable<bool> reedition { get; set; }
        public Nullable<int> nedition { get; set; }
        public Nullable<bool> coedition { get; set; }
        public string coediteur { get; set; }
        public Nullable<bool> contratcoedition { get; set; }
        public Nullable<bool> bcmdcoedit { get; set; }
        public string isbn { get; set; }
        public Nullable<double> prix { get; set; }
    }
}
