//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Droit
    {
        public int code { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string gsm { get; set; }
        public string email { get; set; }
        public string fonction { get; set; }
        public string utilisabilite { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string GestClt { get; set; }
        public string GestAut { get; set; }
        public string GestSt { get; set; }
        public string GestVente { get; set; }
        public string GestDup { get; set; }
        public string GestStat { get; set; }
        public string GestRapp { get; set; }
        public string GestCompta { get; set; }
        public string GestPub { get; set; }
        public string GestAdmin { get; set; }
        public string GestFr { get; set; }
        public string GestDon { get; set; }
        public string GestFourniture { get; set; }
        public string GestDevis { get; set; }
    }
}
