//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int id { get; set; }
        public Nullable<int> NumeroFacture { get; set; }
        public string date_ajout { get; set; }
        public Nullable<int> id_clt { get; set; }
        public string intitule { get; set; }
        public string Adresse { get; set; }
        public string Telephone { get; set; }
        public string L_num_bl { get; set; }
        public string quittance { get; set; }
        public string datequittance { get; set; }
        public string Titre { get; set; }
        public Nullable<double> Montantbrut { get; set; }
        public Nullable<double> remise { get; set; }
        public Nullable<double> totalremise { get; set; }
        public Nullable<double> montantnet { get; set; }
    }
}
