//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fichesuivi
    {
        public int idfiche { get; set; }
        public string ndossier { get; set; }
        public Nullable<int> idagent { get; set; }
        public string agent { get; set; }
        public Nullable<System.DateTime> datereception { get; set; }
        public string observation { get; set; }
        public Nullable<System.DateTime> datemaj { get; set; }
    }
}
