//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ficheauteur
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public Nullable<bool> presentation { get; set; }
        public byte[] fichepresentation { get; set; }
        public byte[] extpr { get; set; }
        public Nullable<bool> biographie { get; set; }
        public byte[] resumebiographie { get; set; }
        public byte[] extbiog { get; set; }
        public Nullable<bool> photoauteur { get; set; }
        public byte[] photo { get; set; }
        public byte[] extphoto { get; set; }
        public Nullable<bool> couverture { get; set; }
        public byte[] propositioncouvert { get; set; }
        public byte[] extcouv { get; set; }
        public Nullable<int> ndossier { get; set; }
    }
}
