//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fourniture
    {
        public int idfour { get; set; }
        public string codefour { get; set; }
        public string famille { get; set; }
        public Nullable<int> idfamille { get; set; }
        public string sousfamille { get; set; }
        public Nullable<int> idsousfamille { get; set; }
        public string designation { get; set; }
        public string fournisseur { get; set; }
        public Nullable<double> quantitenstock { get; set; }
        public Nullable<double> prixAchat { get; set; }
        public byte[] image { get; set; }
        public Nullable<double> seuil { get; set; }
    }
}
