//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fournisseur
    {
        public int codefr { get; set; }
        public Nullable<int> numerofr { get; set; }
        public string raisonfr { get; set; }
        public string responsable { get; set; }
        public string mobile { get; set; }
        public string tel { get; set; }
        public string adress { get; set; }
        public string ville { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public string codepostal { get; set; }
        public byte[] image { get; set; }
    }
}
