//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoLivre
    {
        public int Rang { get; set; }
        public string codeart { get; set; }
        public string titre { get; set; }
        public string imprimerie { get; set; }
        public string auteur { get; set; }
        public string isbn { get; set; }
        public string codeabarre { get; set; }
        public Nullable<double> quantitenstock { get; set; }
    }
}
