//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligne_avoir
    {
        public int id { get; set; }
        public Nullable<int> id_avoir { get; set; }
        public string code_art { get; set; }
        public string designation { get; set; }
        public Nullable<double> quantite { get; set; }
        public Nullable<double> puv { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> remise { get; set; }
        public Nullable<double> prixremise { get; set; }
        public Nullable<int> idauteur { get; set; }
        public string etatpaiement { get; set; }
        public string comment { get; set; }
    }
}
