//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece_bonret
    {
        public int code { get; set; }
        public Nullable<int> Codecumul { get; set; }
        public string Codearticle { get; set; }
        public string nomart { get; set; }
        public Nullable<double> quantite { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
