//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class piece_fact
    {
        public int id_piece { get; set; }
        public string code_piece_u { get; set; }
        public string libelle_piece_u { get; set; }
        public Nullable<double> quantite_piece_u { get; set; }
        public Nullable<int> id_fact { get; set; }
        public Nullable<double> puv { get; set; }
        public Nullable<double> remise { get; set; }
        public Nullable<double> pv { get; set; }
        public Nullable<int> idauteur { get; set; }
    }
}
