//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quittance
    {
        public int id { get; set; }
        public Nullable<int> Nquiitance { get; set; }
        public Nullable<System.DateTime> datequittance { get; set; }
        public string nfact { get; set; }
        public Nullable<int> idclient { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> remise { get; set; }
        public Nullable<double> netapayer { get; set; }
        public string mode { get; set; }
    }
}
