//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reglement
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string nfacture { get; set; }
        public Nullable<int> idclient { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<double> remise { get; set; }
        public Nullable<double> netapayer { get; set; }
        public string typereglement { get; set; }
        public string banque { get; set; }
        public string RIB { get; set; }
        public string ndoc { get; set; }
        public Nullable<System.DateTime> echeance { get; set; }
    }
}
