//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sousfamille
    {
        public int idsousfamille { get; set; }
        public Nullable<int> familleid { get; set; }
        public string familledesign { get; set; }
        public string sousfamilledesign { get; set; }
    }
}
